from __future__ import annotations

from benlab_api.core.constants import ITEM_STATUS_CHOICES, LOCATION_STATUS_CHOICES, LOCATION_USAGE_TAG_CHOICES
from benlab_api.web.template_helpers import (
    MEDIA_KIND_LABELS,
    LOCATION_USAGE_LABELS,
    event_media_entries,
    event_relation_lookup,
    feature_intent,
    feature_tone,
    is_http,
    is_item_alert_status,
    is_location_dirty,
    item_alert_action_label,
    item_alert_level,
    item_media_entries,
    item_relation_lookup,
    location_media_entries,
    location_status_intent,
    media_display_name,
    media_kind,
    normalize_item_stock_status,
    normalize_location_status,
    relation_lookup,
    render_media_gallery,
    render_notification_entry,
    render_resource_entry,
    render_user_log_entry,
    status_intent,
    stock_status_intent,
    uploaded_attachment_url,
    uploaded_media_url,
)


def base_template_context() -> dict:
    return {
        "_": lambda x: x,
        "normalize_item_stock_status": normalize_item_stock_status,
        "stock_status_intent": stock_status_intent,
        "normalize_location_status": normalize_location_status,
        "location_status_intent": location_status_intent,
        "status_intent": status_intent,
        "is_location_dirty": is_location_dirty,
        "is_item_alert_status": is_item_alert_status,
        "item_alert_level": item_alert_level,
        "item_alert_action_label": item_alert_action_label,
        "feature_intent": feature_intent,
        "feature_tone": feature_tone,
        "media_kind": media_kind,
        "media_display_name": media_display_name,
        "media_kind_labels": MEDIA_KIND_LABELS,
        "location_usage_labels": LOCATION_USAGE_LABELS,
        "location_usage_badges": LOCATION_USAGE_LABELS,
        "location_usage_choices": [(tag, LOCATION_USAGE_LABELS.get(tag, tag)) for tag in LOCATION_USAGE_TAG_CHOICES],
        "item_status_choices": ITEM_STATUS_CHOICES,
        "location_status_choices": LOCATION_STATUS_CHOICES,
        "render_media_gallery": render_media_gallery,
        "render_notification_entry": render_notification_entry,
        "render_resource_entry": render_resource_entry,
        "render_user_log_entry": render_user_log_entry,
        "event_relation_lookup": event_relation_lookup,
        "item_relation_lookup": item_relation_lookup,
        "relation_lookup": relation_lookup,
        "uploaded_attachment_url": uploaded_attachment_url,
        "uploaded_media_url": uploaded_media_url,
        "is_http": is_http,
        "item_media_entries": item_media_entries,
        "location_media_entries": location_media_entries,
        "event_media_entries": event_media_entries,
    }
