PYTEST_DISABLE_PLUGIN_AUTOLOAD ?= 1
export PYTEST_DISABLE_PLUGIN_AUTOLOAD

.PHONY: check test ci migrate-smoke

check:
	$(MAKE) -C Benbot check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benben check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benlab check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benoss check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benusy check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benfer check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Bensci check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benome check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)

migrate-smoke:
	$(MAKE) -C Benbot migrate-smoke
	$(MAKE) -C Benlab migrate-smoke
	$(MAKE) -C Benoss migrate-smoke
	$(MAKE) -C Benusy migrate-smoke
	$(MAKE) -C Benome migrate-smoke

ci: check migrate-smoke

test:
	$(MAKE) -C Benbot test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benben test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benlab test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benoss test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benusy test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benfer test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Bensci test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benome test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
