PYTEST_DISABLE_PLUGIN_AUTOLOAD ?= 1
export PYTEST_DISABLE_PLUGIN_AUTOLOAD

.PHONY: check test ci migrate-smoke

check:
	$(MAKE) -C Benbot check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benben check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benlab check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benoss check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benusy check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benfer check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benfast check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benprefs check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benhealth check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benfinance check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benself check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benjournal check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benphoto check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benreel check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benvinyl check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benome check PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)

migrate-smoke:
	$(MAKE) -C Benbot migrate-smoke
	$(MAKE) -C Benlab migrate-smoke
	$(MAKE) -C Benoss migrate-smoke
	$(MAKE) -C Benusy migrate-smoke
	$(MAKE) -C Benome migrate-smoke
	$(MAKE) -C Benprefs migrate-smoke
	$(MAKE) -C Benhealth migrate-smoke
	$(MAKE) -C Benfinance migrate-smoke
	$(MAKE) -C Benself migrate-smoke
	$(MAKE) -C Benjournal migrate-smoke
	$(MAKE) -C Benphoto migrate-smoke
	$(MAKE) -C Benreel migrate-smoke
	$(MAKE) -C Benvinyl migrate-smoke

ci: check migrate-smoke

test:
	$(MAKE) -C Benbot test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benben test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benlab test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benoss test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benusy test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benfer test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benfast test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Bencred/apps/api test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benprefs test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benhealth test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benfinance test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benlink/apps/api test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benself test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benjournal test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benphoto test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benreel test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benvinyl test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
	$(MAKE) -C Benome test PYTEST_DISABLE_PLUGIN_AUTOLOAD=$(PYTEST_DISABLE_PLUGIN_AUTOLOAD)
