"""baseline_schema

Revision ID: e2b74479111a
Revises: 
Create Date: 2026-02-27 10:44:42.409273+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b74479111a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_setting_key'), 'app_setting', ['key'], unique=True)
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('oss_key', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('name_norm', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_norm')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('generated_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_daily_digest', sa.Boolean(), nullable=False),
    sa.Column('source_day', sa.Date(), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('ext', sa.String(length=16), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('oss_key', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source_filters_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generated_asset_public_day_created', 'generated_asset', ['visibility', 'source_day', 'created_at'], unique=False)
    op.create_index(op.f('ix_generated_asset_source_day'), 'generated_asset', ['source_day'], unique=False)
    op.create_index('ix_generated_asset_user_created', 'generated_asset', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_generated_asset_user_id'), 'generated_asset', ['user_id'], unique=False)
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('preview', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_content_id'), 'record', ['content_id'], unique=True)
    op.create_index('ix_record_user_created', 'record', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_record_user_id'), 'record', ['user_id'], unique=False)
    op.create_index('ix_record_visibility_created', 'record', ['visibility', 'created_at'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comment_record_created', 'comment', ['record_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_comment_record_id'), 'comment', ['record_id'], unique=False)
    op.create_index(op.f('ix_comment_user_id'), 'comment', ['user_id'], unique=False)
    op.create_table('daily_digest_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('blog_asset_id', sa.Integer(), nullable=True),
    sa.Column('podcast_asset_id', sa.Integer(), nullable=True),
    sa.Column('poster_asset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blog_asset_id'], ['generated_asset.id'], ),
    sa.ForeignKeyConstraint(['podcast_asset_id'], ['generated_asset.id'], ),
    sa.ForeignKeyConstraint(['poster_asset_id'], ['generated_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_digest_job_day'), 'daily_digest_job', ['day'], unique=False)
    op.create_table('record_tags',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_tags')
    op.drop_index(op.f('ix_daily_digest_job_day'), table_name='daily_digest_job')
    op.drop_table('daily_digest_job')
    op.drop_index(op.f('ix_comment_user_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_record_id'), table_name='comment')
    op.drop_index('ix_comment_record_created', table_name='comment')
    op.drop_table('comment')
    op.drop_index('ix_record_visibility_created', table_name='record')
    op.drop_index(op.f('ix_record_user_id'), table_name='record')
    op.drop_index('ix_record_user_created', table_name='record')
    op.drop_index(op.f('ix_record_content_id'), table_name='record')
    op.drop_table('record')
    op.drop_index(op.f('ix_generated_asset_user_id'), table_name='generated_asset')
    op.drop_index('ix_generated_asset_user_created', table_name='generated_asset')
    op.drop_index(op.f('ix_generated_asset_source_day'), table_name='generated_asset')
    op.drop_index('ix_generated_asset_public_day_created', table_name='generated_asset')
    op.drop_table('generated_asset')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('content')
    op.drop_index(op.f('ix_app_setting_key'), table_name='app_setting')
    op.drop_table('app_setting')
    # ### end Alembic commands ###

