"""baseline schema

Revision ID: 43b1d4e82862
Revises: 
Create Date: 2026-03-01 05:18:47.531814+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '43b1d4e82862'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_metric_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform_coef', sa.Float(), nullable=False),
    sa.Column('like_weight', sa.Float(), nullable=False),
    sa.Column('favorite_weight', sa.Float(), nullable=False),
    sa.Column('share_weight', sa.Float(), nullable=False),
    sa.Column('view_weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_metric_configs_platform'), 'platform_metric_configs', ['platform'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_reward', sa.Float(), nullable=False),
    sa.Column('accept_limit', sa.Integer(), nullable=True),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'cancelled', name='taskstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_platform'), 'tasks', ['platform'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('users',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('real_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('follower_total', sa.Integer(), nullable=False),
    sa.Column('avg_views', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.Enum('pending', 'under_review', 'approved', 'rejected', name='reviewstatus'), nullable=False),
    sa.Column('review_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'blogger', name='role'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_review_status'), 'users', ['review_status'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('accepted', 'in_review', 'rejected', 'completed', 'cancelled', name='assignmentstatus'), nullable=False),
    sa.Column('post_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reject_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metric_sync_status', sa.Enum('normal', 'manual_required', 'manual_pending_review', 'manual_approved', 'manual_rejected', name='metricsyncstatus'), nullable=False),
    sa.Column('last_sync_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_metric_sync_status'), 'assignments', ['metric_sync_status'], unique=False)
    op.create_index(op.f('ix_assignments_status'), 'assignments', ['status'], unique=False)
    op.create_index(op.f('ix_assignments_task_id'), 'assignments', ['task_id'], unique=False)
    op.create_index(op.f('ix_assignments_user_id'), 'assignments', ['user_id'], unique=False)
    op.create_table('douyin_accounts',
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sec_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_douyin_accounts_account_id'), 'douyin_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_douyin_accounts_user_id'), 'douyin_accounts', ['user_id'], unique=False)
    op.create_table('payout_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payout_method', sa.Enum('bank_card', 'alipay', 'wechat_pay', 'paypal', 'other', name='payoutmethod'), nullable=False),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_qr_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bank_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wechat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wechat_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wechat_qr_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alipay_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alipay_account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alipay_qr_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_infos_user_id'), 'payout_infos', ['user_id'], unique=True)
    op.create_table('settlement_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_records_admin_id'), 'settlement_records', ['admin_id'], unique=False)
    op.create_index(op.f('ix_settlement_records_paid_at'), 'settlement_records', ['paid_at'], unique=False)
    op.create_index(op.f('ix_settlement_records_user_id'), 'settlement_records', ['user_id'], unique=False)
    op.create_table('user_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activity_logs_action_type'), 'user_activity_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_user_activity_logs_user_id'), 'user_activity_logs', ['user_id'], unique=False)
    op.create_table('weibo_accounts',
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weibo_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weibo_accounts_account_id'), 'weibo_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_weibo_accounts_user_id'), 'weibo_accounts', ['user_id'], unique=False)
    op.create_table('xiaohongshu_accounts',
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('xhs_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xiaohongshu_accounts_account_id'), 'xiaohongshu_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_xiaohongshu_accounts_user_id'), 'xiaohongshu_accounts', ['user_id'], unique=False)
    op.create_table('manual_metric_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('favorites', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('review_status', sa.Enum('pending', 'approved', 'rejected', name='manualmetricreviewstatus'), nullable=False),
    sa.Column('review_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_metric_submissions_assignment_id'), 'manual_metric_submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_manual_metric_submissions_review_status'), 'manual_metric_submissions', ['review_status'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('favorites', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('auto', 'manual', name='metricsource'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_assignment_id'), 'metrics', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_metrics_source'), 'metrics', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_source'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_assignment_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_manual_metric_submissions_review_status'), table_name='manual_metric_submissions')
    op.drop_index(op.f('ix_manual_metric_submissions_assignment_id'), table_name='manual_metric_submissions')
    op.drop_table('manual_metric_submissions')
    op.drop_index(op.f('ix_xiaohongshu_accounts_user_id'), table_name='xiaohongshu_accounts')
    op.drop_index(op.f('ix_xiaohongshu_accounts_account_id'), table_name='xiaohongshu_accounts')
    op.drop_table('xiaohongshu_accounts')
    op.drop_index(op.f('ix_weibo_accounts_user_id'), table_name='weibo_accounts')
    op.drop_index(op.f('ix_weibo_accounts_account_id'), table_name='weibo_accounts')
    op.drop_table('weibo_accounts')
    op.drop_index(op.f('ix_user_activity_logs_user_id'), table_name='user_activity_logs')
    op.drop_index(op.f('ix_user_activity_logs_action_type'), table_name='user_activity_logs')
    op.drop_table('user_activity_logs')
    op.drop_index(op.f('ix_settlement_records_user_id'), table_name='settlement_records')
    op.drop_index(op.f('ix_settlement_records_paid_at'), table_name='settlement_records')
    op.drop_index(op.f('ix_settlement_records_admin_id'), table_name='settlement_records')
    op.drop_table('settlement_records')
    op.drop_index(op.f('ix_payout_infos_user_id'), table_name='payout_infos')
    op.drop_table('payout_infos')
    op.drop_index(op.f('ix_douyin_accounts_user_id'), table_name='douyin_accounts')
    op.drop_index(op.f('ix_douyin_accounts_account_id'), table_name='douyin_accounts')
    op.drop_table('douyin_accounts')
    op.drop_index(op.f('ix_assignments_user_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_task_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_status'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_metric_sync_status'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_review_status'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_platform'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_platform_metric_configs_platform'), table_name='platform_metric_configs')
    op.drop_table('platform_metric_configs')
    # ### end Alembic commands ###
