from fastapi import APIRouter

from benusy_api.core.config import settings
from benusy_api.schemas.public_config import HomepageConfigRead, OSSPublicConfigRead, PublicConfigRead

router = APIRouter(prefix="/public", tags=["public"])


@router.get("/config", response_model=PublicConfigRead)
def get_public_config() -> PublicConfigRead:
    return PublicConfigRead(
        homepage=HomepageConfigRead(
            site_name=settings.homepage_site_name,
            nav_brand=settings.homepage_nav_brand,
            nav_features_label=settings.homepage_nav_features_label,
            nav_scenes_label=settings.homepage_nav_scenes_label,
            nav_workflow_label=settings.homepage_nav_workflow_label,
            nav_contact_label=settings.homepage_nav_contact_label,
            hero_kicker=settings.homepage_hero_kicker,
            hero_title=settings.homepage_hero_title,
            hero_subtitle=settings.homepage_hero_subtitle,
            hero_image_url=settings.homepage_hero_image_url,
            hero_primary_button_text=settings.homepage_hero_primary_button_text,
            hero_primary_button_href=settings.homepage_hero_primary_button_href,
            hero_secondary_button_text=settings.homepage_hero_secondary_button_text,
            hero_secondary_button_href=settings.homepage_hero_secondary_button_href,
            hero_photo_primary_caption=settings.homepage_hero_photo_primary_caption,
            hero_photo_secondary_caption=settings.homepage_hero_photo_secondary_caption,
            hero_photo_tertiary_caption=settings.homepage_hero_photo_tertiary_caption,
            hero_proof_primary_title=settings.homepage_hero_proof_primary_title,
            hero_proof_primary_body=settings.homepage_hero_proof_primary_body,
            hero_proof_secondary_title=settings.homepage_hero_proof_secondary_title,
            hero_proof_secondary_body=settings.homepage_hero_proof_secondary_body,
            hero_top_note_label=settings.homepage_hero_top_note_label,
            hero_top_note_title=settings.homepage_hero_top_note_title,
            hero_bottom_note_label=settings.homepage_hero_bottom_note_label,
            hero_bottom_note_title=settings.homepage_hero_bottom_note_title,
            showcase_label=settings.homepage_showcase_label,
            showcase_title=settings.homepage_showcase_title,
            showcase_subtitle=settings.homepage_showcase_subtitle,
            showcase_primary_title=settings.homepage_showcase_primary_title,
            showcase_primary_body=settings.homepage_showcase_primary_body,
            showcase_secondary_title=settings.homepage_showcase_secondary_title,
            showcase_secondary_body=settings.homepage_showcase_secondary_body,
            showcase_tertiary_title=settings.homepage_showcase_tertiary_title,
            showcase_tertiary_body=settings.homepage_showcase_tertiary_body,
            capabilities_label=settings.homepage_capabilities_label,
            capabilities_title=settings.homepage_capabilities_title,
            capabilities_subtitle=settings.homepage_capabilities_subtitle,
            capability_highlight_one=settings.homepage_capability_highlight_one,
            capability_highlight_two=settings.homepage_capability_highlight_two,
            capability_highlight_three=settings.homepage_capability_highlight_three,
            capability_spotlight_label=settings.homepage_capability_spotlight_label,
            capability_spotlight_title=settings.homepage_capability_spotlight_title,
            capability_spotlight_body=settings.homepage_capability_spotlight_body,
            capability_card_one_label=settings.homepage_capability_card_one_label,
            capability_card_one_title=settings.homepage_capability_card_one_title,
            capability_card_one_body=settings.homepage_capability_card_one_body,
            capability_card_two_label=settings.homepage_capability_card_two_label,
            capability_card_two_title=settings.homepage_capability_card_two_title,
            capability_card_two_body=settings.homepage_capability_card_two_body,
            capability_card_three_label=settings.homepage_capability_card_three_label,
            capability_card_three_title=settings.homepage_capability_card_three_title,
            capability_card_three_body=settings.homepage_capability_card_three_body,
            workflow_label=settings.homepage_workflow_label,
            workflow_title=settings.homepage_workflow_title,
            workflow_subtitle=settings.homepage_workflow_subtitle,
            workflow_step_one_title=settings.homepage_workflow_step_one_title,
            workflow_step_one_body=settings.homepage_workflow_step_one_body,
            workflow_step_two_title=settings.homepage_workflow_step_two_title,
            workflow_step_two_body=settings.homepage_workflow_step_two_body,
            workflow_step_three_title=settings.homepage_workflow_step_three_title,
            workflow_step_three_body=settings.homepage_workflow_step_three_body,
            workflow_step_four_title=settings.homepage_workflow_step_four_title,
            workflow_step_four_body=settings.homepage_workflow_step_four_body,
            workflow_summary_label=settings.homepage_workflow_summary_label,
            workflow_summary_title=settings.homepage_workflow_summary_title,
            workflow_summary_body=settings.homepage_workflow_summary_body,
            merchant_notice_title=settings.homepage_merchant_notice_title,
            merchant_notice_text=settings.homepage_merchant_notice_text,
            merchant_service_publish_text=settings.homepage_merchant_service_publish_text,
            merchant_service_account_text=settings.homepage_merchant_service_account_text,
            merchant_service_no_register_text=settings.homepage_merchant_service_no_register_text,
            merchant_contact_phone=settings.homepage_merchant_contact_phone,
            merchant_contact_wechat=settings.homepage_merchant_contact_wechat,
            merchant_contact_email=settings.homepage_merchant_contact_email,
            contact_section_label=settings.homepage_contact_section_label,
            contact_section_title=settings.homepage_contact_section_title,
            contact_section_subtitle=settings.homepage_contact_section_subtitle,
            contact_info_title=settings.homepage_contact_info_title,
            contact_form_label=settings.homepage_contact_form_label,
            contact_form_title=settings.homepage_contact_form_title,
            contact_form_subtitle=settings.homepage_contact_form_subtitle,
            contact_form_button_text=settings.homepage_contact_form_button_text,
            contact_address=settings.homepage_contact_address,
            contact_phone=settings.homepage_contact_phone,
            contact_email=settings.homepage_contact_email,
            footer_about_title=settings.homepage_footer_about_title,
            footer_about_body=settings.homepage_footer_about_body,
            footer_links_title=settings.homepage_footer_links_title,
            footer_legal_title=settings.homepage_footer_legal_title,
            footer_privacy_label=settings.homepage_footer_privacy_label,
            footer_terms_label=settings.homepage_footer_terms_label,
            footer_cookie_label=settings.homepage_footer_cookie_label,
            footer_subscribe_title=settings.homepage_footer_subscribe_title,
            footer_subscribe_body=settings.homepage_footer_subscribe_body,
            footer_subscribe_placeholder=settings.homepage_footer_subscribe_placeholder,
            footer_subscribe_button=settings.homepage_footer_subscribe_button,
            footer_copyright=settings.homepage_footer_copyright,
        ),
        oss=OSSPublicConfigRead(
            enabled=settings.oss_enabled(),
            endpoint=settings.aliyun_oss_endpoint,
            bucket=settings.aliyun_oss_bucket,
            prefix=settings.aliyun_oss_prefix,
        ),
    )
