"""baseline_schema

Revision ID: 43cc4d187676
Revises: 
Create Date: 2026-02-27 10:44:41.504348+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43cc4d187676'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('detail_refs', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('features', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('quantity_desc', sa.String(length=120), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('purchase_link', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items'))
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('coordinate_source', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('detail_refs', sa.Text(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('detail_link', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], name=op.f('fk_locations_parent_id_locations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('feedback_log', sa.Text(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_members'))
    )
    op.create_index(op.f('ix_members_username'), 'members', ['username'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('detail_link', sa.String(length=255), nullable=False),
    sa.Column('feedback_log', sa.Text(), nullable=False),
    sa.Column('allow_participant_edit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['members.id'], name=op.f('fk_events_owner_id_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_owner_id'), 'events', ['owner_id'], unique=False)
    op.create_table('item_locations',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_locations_item_id_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_item_locations_location_id_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'location_id', name=op.f('pk_item_locations'))
    )
    op.create_table('item_members',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_members_item_id_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_item_members_member_id_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'member_id', name=op.f('pk_item_members'))
    )
    op.create_table('location_members',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_location_members_location_id_locations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_location_members_member_id_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'member_id', name=op.f('pk_location_members'))
    )
    op.create_table('member_follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['members.id'], name=op.f('fk_member_follows_followed_id_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['members.id'], name=op.f('fk_member_follows_follower_id_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id', name=op.f('pk_member_follows'))
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['members.id'], name=op.f('fk_messages_receiver_id_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['members.id'], name=op.f('fk_messages_sender_id_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(item_id IS NOT NULL) + (location_id IS NOT NULL) + (event_id IS NOT NULL) = 1', name=op.f('ck_attachments_single_owner')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_attachments_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_attachments_item_id_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_attachments_location_id_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    op.create_index(op.f('ix_attachments_event_id'), 'attachments', ['event_id'], unique=False)
    op.create_index(op.f('ix_attachments_item_id'), 'attachments', ['item_id'], unique=False)
    op.create_index(op.f('ix_attachments_location_id'), 'attachments', ['location_id'], unique=False)
    op.create_table('event_items',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_items_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_event_items_item_id_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'item_id', name=op.f('pk_event_items'))
    )
    op.create_table('event_locations',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_locations_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_event_locations_location_id_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'location_id', name=op.f('pk_event_locations'))
    )
    op.create_table('event_participants',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_participants_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_event_participants_member_id_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'member_id', name=op.f('pk_event_participants'))
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_logs_event_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_logs_item_id_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_logs_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['members.id'], name=op.f('fk_logs_user_id_members'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logs'))
    )
    op.create_index(op.f('ix_logs_event_id'), 'logs', ['event_id'], unique=False)
    op.create_index(op.f('ix_logs_item_id'), 'logs', ['item_id'], unique=False)
    op.create_index(op.f('ix_logs_location_id'), 'logs', ['location_id'], unique=False)
    op.create_index(op.f('ix_logs_user_id'), 'logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_user_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_location_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_item_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_event_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_table('event_participants')
    op.drop_table('event_locations')
    op.drop_table('event_items')
    op.drop_index(op.f('ix_attachments_location_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_item_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_event_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_table('messages')
    op.drop_table('member_follows')
    op.drop_table('location_members')
    op.drop_table('item_members')
    op.drop_table('item_locations')
    op.drop_index(op.f('ix_events_owner_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_members_username'), table_name='members')
    op.drop_table('members')
    op.drop_table('locations')
    op.drop_table('items')
    # ### end Alembic commands ###

