import base64
import hashlib
import hmac
import json
import secrets
import time
from typing import Optional

from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer

from benfer_api.core.config import get_settings

settings = get_settings()
security = HTTPBearer(auto_error=False)


def _urlsafe_b64decode(raw: str) -> str:
    padding = "=" * (-len(raw) % 4)
    return base64.urlsafe_b64decode((raw + padding).encode()).decode()


def verify_sso_token(token: str) -> dict:
    """Verify token format generated by Benbot: base64url(json_payload.signature)."""
    try:
        decoded = _urlsafe_b64decode(token)
        dot_pos = decoded.rfind(".")
        if dot_pos == -1:
            raise ValueError("invalid token format")

        data, signature = decoded[:dot_pos], decoded[dot_pos + 1 :]
        expected_signature = hmac.new(
            settings.SSO_SECRET.encode(),
            data.encode(),
            hashlib.sha256,
        ).hexdigest()

        if not hmac.compare_digest(signature, expected_signature):
            raise ValueError("invalid token signature")

        payload = json.loads(data)
        exp = int(payload.get("e", 0))
        if exp < time.time():
            raise ValueError("token expired")

        user_id = payload.get("u")
        if not user_id:
            raise ValueError("missing user id")

        return {
            "user_id": user_id,
            "role": payload.get("r"),
            "exp": exp,
        }
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or expired token",
        ) from exc


def create_session_token(
    user_id: str,
    role: Optional[str] = None,
    ttl_seconds: Optional[int] = None,
) -> tuple[str, int]:
    """Create a Benfer-local session token in the same signed payload format."""
    expires_in = ttl_seconds or settings.SESSION_TOKEN_TTL_SECONDS
    exp = int(time.time()) + expires_in
    payload = {
        "u": user_id,
        "r": role or "user",
        "e": exp,
        "n": secrets.token_hex(8),
        "src": "benfer",
    }
    data = json.dumps(payload, separators=(",", ":"))
    signature = hmac.new(
        settings.SSO_SECRET.encode(),
        data.encode(),
        hashlib.sha256,
    ).hexdigest()
    token = base64.urlsafe_b64encode(f"{data}.{signature}".encode()).decode()
    return token, exp


async def get_optional_current_user(
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(security),
) -> Optional[dict]:
    """Return current user when token exists, otherwise None."""
    if not credentials:
        return None
    return verify_sso_token(credentials.credentials)


async def get_current_user(
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(security),
) -> dict:
    """Require authentication and return current user."""
    user = await get_optional_current_user(credentials)
    if not user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Not authenticated",
        )
    return user
